config/routes.rb
Rails.application.routes.draw do
  devise_for :logins
  resources :posts
  resources :users
  get 'users/:id' => 'users#show'
  post 'users/:id' => 'users#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/login.rb
class Login < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    mount_uploader :image, ImagesUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if params[:name] && params[:age]
      @users = User.where(name: params[:name]).where(age: params[:age])
      flash[:message] = "該当なし" if params[:name].blank?
    else
      @users = User.all
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if params[:loginname]
      @user = User.new(name: params[:loginname])
      @user.save
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :age, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
<div class="container">
  <div class="navbar-header">
    
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    
  </div>
  
  <div class="collapse navbar-collapse" id="myNavbar">
    <ul class="nav navbar-nav">
      <li><a href="/users">home</a></li>
      <li><%= link_to 'New User', new_user_path %></li>
      <li>
        <%= form_tag(users_path, method: "get", class: "navbar-form navbar-left") do %>
          <% 
          list = {
            "1歳" => "1",
            "2歳" => "2",
            "3歳" => "3",
            "4歳" => "4",
            "5歳" => "5",
            "6歳" => "6",
            "7歳" => "7"
          }
          %>
          <%= select_tag :age, options_for_select(list), class: "form-control", prompt: "選択してください" %>
          ×
          <%= text_field_tag :name, "" ,class: "form-control", placeholder: "name" %>
          <%= submit_tag '検索', class: "btn btn-default" %>
        <% end %>
      </li>
      <% if login_signed_in? %>
        <strong><%= link_to current_login.loginname, "/" %></strong>
          <li><%= link_to 'プロフィール変更', edit_login_registration_path %></li>
          <li><%= link_to 'ログアウト', destroy_login_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'サインアップ', new_login_registration_path %></li>
        <li><%= link_to 'ログイン', new_login_session_path %></li>
      <% end %>
    </ul>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/stylesheets.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
  </head>

  <body>
  <%= render partial: 'layouts/header' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div id="my-slider" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li date-target="#my-slider" data-slide-to="0" class="active"></li>
              <li date-target="#my-slider" data-slide-to="1"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
              <div class="item active">
                <img src="/hogehoge.jpg" width="100%" height="80%" alt="犬の画像" />
                <div class="carousel-caption">
                  <h1>犬の画像</h1>
                </div>
              </div>
              <div class="item">
                <img src="/hogehoge.jpg" width="100%" height="80%" alt="犬の画像" />
                  <div class="carousel-caption">
                    <h1>犬の画像</h1>
                  </div>
                </div>
              </div>
              <a class="left carousel-control" href="#my-slider" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#my-slider" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    <div class="container">
    <%= yield %>
    </div>
    <hr>
    <%= p params %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-6">
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-8">
<h1>ようこそ</h1>
<p>トップページです。</p>

<table border="1" cellspacing='5'>
  <thead>
    <tr>
      <th>投稿画像</th>
      <th>作成日時</th>
      <th>名前</th>
      <th>年齢</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.image.to_s, style: "width: 100px;" %></td>
        <td><%= user.created_at.strftime('%Y-%m-%d %H-%M-%S') %></td>
        <td><%= user.name %></td>
        <td><%= user.age %></td>
        <td><%= link_to 'Show', user, class: "square_btn", style: "margin: 5px;" %></td>
        <td><%= link_to 'Edit', edit_user_path(user), class: "btn btn-success", style: "margin: 5px;" %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", style: "margin: 5px;" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= flash[:message] %>
<br>

</div>
<div class="col-md-4">
  <!-- ここ  -->
  <img src="/hogehoge.jpg" alt="hoge" class="img-thumbnail">
  <br>
　<img src="/hogehoge.jpg" alt="hoge" class="img-thumbnail">
  <br><br>
  <!-- ここ -->
  <div class="list-group">
    <a href="#" class="list-group-item active">テキストテキストテキスト</a>
    <a href="#" class="list-group-item">テキストテキストテキスト</a>
    <a href="#" class="list-group-item">テキストテキストテキスト</a>
    <a href="#" class="list-group-item">テキストテキストテキスト</a>
    <a href="#" class="list-group-item">テキストテキストテキスト</a>
    <a href="#" class="list-group-item">テキストテキストテキスト</a>
    <a href="#" class="list-group-item">テキストテキストテキスト</a>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<%= form_tag(url_for(:action => 'show'), :remote => true) do %>
  <h1><%= button_tag type: "submit", class: "btn btn-primary" do %>
    <i class="fas fa-thumbs-up"></i><% end %></h1>
  <%= hidden_field_tag :loginname, "hoge" %>

<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/show.js.erb
$('h1').html("<i class='fas fa-thumbs-up'></i>");